### ISSUE TITLE
[PE-D] Contact with the same name cannot be added

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W17-3/tp#101]
What if I have friends with the same name? Or can even extend the logic checking to check phone number/email instead

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: AdrianOngJJ/ped#5

**Comment by leeyiheng12** [comment]
The logic is updated to recognise two people with the same phone number to have the same identity. Good catch, thanks!
