### ISSUE TITLE
[PE-D] Undo command not working

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W17-3/tp#106]
Undo command not working after deleting a package

![image.png](https://raw.githubusercontent.com/putaojuice/ped/main/files/8ace833a-7db7-4fad-8339-fca9c2900474.png)

![image.png](https://raw.githubusercontent.com/putaojuice/ped/main/files/687b804d-e402-4ebd-a977-db3899a1b7c4.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: putaojuice/ped#10

**Comment by jiewei98** [comment]
Fixed documentation to explain that undo only works for commands that alter AddressBook
