### ISSUE TITLE
[PE-D] Adding new packages without using `addp`

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W17-3/tp#110]
If I add a new contact using `i/[NEW_PACKAGE]`, the package will be created. Not sure if this effect is intended.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: AdrianOngJJ/ped#6

**Comment by leeyiheng12** [comment]
Hello, the effect is intended. We should have clarified it in the documentation. Thanks for the heads up!
