### ISSUE TITLE
[PE-D] Export command hangs the application

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W17-3/tp#111]
Im using macbook pro 2020 with macOS 11.6, when i try the export command the application hangs and does not respond, tried multiple times. The log says saving to csv, perhaps is because i used special characters in the package description/details and it caused the saving to not work.

![image.png](https://raw.githubusercontent.com/putaojuice/ped/main/files/b58340ac-6f83-4f27-a05b-728658a77db1.png)

![image.png](https://raw.githubusercontent.com/putaojuice/ped/main/files/4dd9e1da-df17-4afc-8dda-777a1c2670c4.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: putaojuice/ped#11

**Comment by leeyiheng12** [comment]
Hello, we changed our file chooser to one that worked for non-Windows systems. Thanks for the catch!
