### ISSUE TITLE
[PE-D] Package does not get deleted from the client after using `deletep`

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W17-3/tp#112]
![image.png](https://raw.githubusercontent.com/raynerljm/ped/main/files/6f3d4b4f-70c4-4210-a9a6-416f8fa51f20.png)

Steps to reproduce:
1. Add a package to a client
2. Use the command `deletep` to delete that same package

Expected outcome:
- The client should no longer have the package as it does not exist

Actual outcome:
- The client still has the package 
- eg. John Doe still has the `package1` insurance package even after deleting it

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: raynerljm/ped#9

**Comment by leeyiheng12** [comment]
Hello, thanks for raising this up! We have changed the implementation of the deletion of packages, such that this will not occur anymore - deleting a package in use by a person will not be allowed.
