### ISSUE TITLE
[PE-D] Using the `import` command crashes the application

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W17-3/tp#117]
Steps to reproduce:
1. Use the `import` command

Expected outcome:
1. A window will open allowing me to select a csv file to import

Actual outcome:
1. My application loads for a few minutes and crashes

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: raynerljm/ped#10

**Comment by leeyiheng12** [comment]
Hello, we changed our file chooser to one that works for non-Windows systems. Thanks for the catch!
