### ISSUE TITLE
[PE-D] edit person's i/

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103-W17-3/tp#125]
Same as issue #6

On top of that, say **Package** list have `package1`.

If I `edit 1 i/package2`, `package2` will appear in **Package** list. But no one uses `package1`. So should `package1` be automatically removed or not? Cannot find in UG hence reporting as a bug.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: AdrianOngJJ/ped#9

**Comment by leeyiheng12** [comment]
Package1 will not be removed, since we are just storing a list of packages that have been added before. Will update the UG to reflect this, thanks!
