### ISSUE TITLE
[PE-D] Application does not response when executing export command

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W17-3/tp#145]
Application does not response when executing export command after 2 minutes
![Screenshot 2022-04-01 at 4.10.29 PM.png](https://raw.githubusercontent.com/ro4k9/ped/main/files/685e0a32-620d-4773-9be4-adb841478b20.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: ro4k9/ped#14

**Comment by leeyiheng12** [comment]
Hello, we changed our file chooser to one that works for non-Windows systems. Thanks for the catch!
