### ISSUE TITLE
[PE-D] Application does not response when executing import command #14

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W17-3/tp#146]
![Screenshot 2022-04-01 at 4.14.30 PM.png](https://raw.githubusercontent.com/ro4k9/ped/main/files/5caa42b4-6f60-4b65-adec-29549aaa86ab.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: ro4k9/ped#15

**Comment by leeyiheng12** [comment]
Hello, we changed our file chooser to one that worked for non-Windows systems. Thanks for the catch!
