### ISSUE TITLE
[PE-D] `help` command sends back to AB3

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W17-3/tp#92]
![image.png](https://raw.githubusercontent.com/AdrianOngJJ/ped/main/files/45817598-9cd9-4472-9397-3fa799f2a0e8.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: AdrianOngJJ/ped#3

**Comment by leeyiheng12** [comment]
Changed, thanks!
