### ISSUE TITLE
[PE-D] New package allows special characters

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W17-3/tp#99]
As title, i don't think this should be allowed?

![image.png](https://raw.githubusercontent.com/putaojuice/ped/main/files/509b265d-5b2f-405b-a5c4-96c9128cc254.png)

-------------
Labels: `type.FeatureFlaw` `severity.High`
original: putaojuice/ped#7

**Comment by leeyiheng12** [comment]
Hello! This is similar to https://github.com/AY2122S2-CS2103-W17-3/tp/issues/100, which I believe was submitted by you as well.

To reiterate, with the exception of a few fields, we do not usually restrict the values that a user can key in. In this case, we do not restrict an insurance package description to only contain alphanumeric values. This is not a bug.

However, if you believe that this should be changed, do let us know!
